guests=['olga' , 'pol','jim', 'scott', 'lora', 'peppy', 'minion']
print(guests)
message=('I,d like to invite '+guests[-1].title()+' '+ 'for fucking a bitch'+'!')
print(message)
message_2=('I,d like to invite '+guests[0].title()+' '+ 'for fucking a bitch'+'!')
print(message_2)
message_3=('I,d like to invite '+guests[-2].title()+' '+ 'for fucking a bitch'+'!')
print(message_3)
guests_popped=(guests.pop(-2))
print(guests_popped)
print(guests)
guests.append('jila')
print(guests)
message_4=('I,d like to invite '+guests[-1].title()+' '+ 'for fucking a bitch'+'!')
print(message_4)
guests.append('tom')
guests.append('farhad')
guests.append('marta')
print(guests)
guests.insert(0, 'kelly')
print(guests)
guests.insert(4, 'katryn')
print(guests)
message_5=('I,d like to invite '+guests[0].title()+' '+ 'for fucking a bitch'+'!')
print(message_5)
message_6=('I,d like to invite '+guests[4].title()+' '+ 'for fucking a bitch'+'!')
print(message_6)
message_7=('I,d like to invite '+guests[-2].title()+' '+ 'for fucking a bitch'+'!')
print(message_7)
guests_popped=(guests.pop(0))
print(guests_popped)
message_8=('Sorry ,but ,'+' '+guests_popped.title()+' '+'can,t fuck the bitch'+'.' )
print(message_8)
guests_popped=guests.pop(-1)
print(guests_popped)
message_9=('Sorry ,but '+' '+guests_popped.title()+' '+'can,t fuck the bitch'+'.')
print(message_9)
guests_popped=guests.pop(-3)
print(guests)
print(guests_popped)
message_10=('Sorry ,but ,'+' '+guests_popped.title()+' '+'can,t fuck the bitch'+'.')
print(message_10)
message_11=('As I think, only two guests are good enough ,to fuck the bitch. They are '+guests[2].title()+' '+'and '+guests[-1].title()+'!')
print(message_11)
print(guests)
del guests[0]
print(guests)
del guests[-2]
del guests[-3]
print(guests)
del guests[0]
print(guests)
guests.remove('minion')
print(guests)
guests.remove('katryn')
print(guests)
guests.remove('scott')
print(guests)
del guests[0]
print(guests)
del guests[0]
print(guests)