car_list=['ferrary','alfa_romeo','bugatty','lamborgini','zaporozhets']
len(car_list)
print(car_list)
car_list.append('mazer')
print(car_list)
car_list.sort()
print(car_list)
car_list.sort(reverse=True)
print(car_list)
print('original')
print(car_list)
print('sorted')
print(sorted(car_list))
print('original again')
print(sorted(car_list,reverse=True))
print(car_list)
len(car_list)
car_list.reverse()
print(car_list)
len(  car_list)

