first_list=['dog','cat','poppy','u-hu',3]
print(first_list)
first_list.append('vzhik')
print(first_list)
first_list[0]=('pyp')
print(first_list)
first_list.append('tryn')
print(first_list[::-1])
first_list.insert(2,'crocodyle')
print(first_list)
del first_list[2]
print(first_list)
#popped_motorcycle = motorcycles.pop(0)
#print(popped_motorcycle)
popped_first_list=first_list.pop(0)
print(popped_first_list)
message=('My last animal was '+popped_first_list)
print(message)
popped_first_list=first_list.pop(0)
print(popped_first_list)